from biogeme.expressions import *
pass_ID=Variable('pass_ID')
scenario=Variable('scenario')
time_crit=Variable('time_crit')
now_ivt_4=Variable('now_ivt_4')
now_ivt_3=Variable('now_ivt_3')
wait_ivt_3=Variable('wait_ivt_3')
wait_ivt_2=Variable('wait_ivt_2')
WT_time=Variable('WT_time')
output_choice=Variable('output_choice')
