from biogeme.expressions import *
pass_ID=Variable('pass_ID')
scenario=Variable('scenario')
time_crit=Variable('time_crit')
B_cr4first=Variable('B_cr4first')
B_cr3first=Variable('B_cr3first')
B_cr3second=Variable('B_cr3second')
B_cr2second=Variable('B_cr2second')
commuter=Variable('commuter')
age_50_65=Variable('age_50_65')
age_65=Variable('age_65')
IVT_time=Variable('IVT_time')
WT_time=Variable('WT_time')
output_choice=Variable('output_choice')
